# https://packaging.python.org/guides/supporting-windows-using-appveyor/#appveyor-yml

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # Install required python packages
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe intel-sde-downloader.py sde-external-8.35.0-2019-03-11-win.tar.bz2"
  - printf "de8389e14cead880544a231796b459b66c013b0ed29a4c0fe3d5867fa8da19c3 *sde-external-8.35.0-2019-03-11-win.tar.bz2" | sha256sum -c -
