# https://packaging.python.org/guides/supporting-windows-using-appveyor/#appveyor-yml

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

install:
  # Install required python packages
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe intel-sde-downloader.py sde-external-8.50.0-2020-03-26-win.tar.bz2"
  - printf "70299d636c01bb2f183f6019c3fe48f07f208858aeae0ce5a54c0e9ef2dcdbb8 *sde-external-8.50.0-2020-03-26-win.tar.bz2" | sha256sum -c -
