# https://packaging.python.org/guides/supporting-windows-using-appveyor/#appveyor-yml

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # Install required python packages
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe intel-sde-downloader.py sde-external-8.33.0-2019-02-07-win.tar.bz2"
  - printf "26fcf8ffe62f1d7e96359d1f7eae2ca155f430cf44d3ca466bbda20531bc9050 *sde-external-8.33.0-2019-02-07-win.tar.bz2" | sha256sum -c -
