# https://docs.travis-ci.com/user/languages/python/#python-versions

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
script:
  - python ./intel-sde-downloader.py sde-external-8.50.0-2020-03-26-lin.tar.bz2
  - echo "ecabeb26c3b35cfe72b6ba017b1ba1849516b4b077c2b59e730a0fdf00324be4  sde-external-8.50.0-2020-03-26-lin.tar.bz2" | sha256sum -c -
