# https://docs.travis-ci.com/user/languages/python/#python-versions

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
script:
  - python ./intel-sde-downloader.py sde-external-8.49.0-2020-03-17-lin.tar.bz2
  - echo "ed426d46f5b74a803c740499b8166da32b58d20259146ee05a9987091f94d8e0  sde-external-8.49.0-2020-03-17-lin.tar.bz2" | sha256sum -c -
